<?php

namespace MonbonHLM\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends EntityRepository
{
    public function RecupererUtilisateurs($page=1, $maxperpage=30) {
        $query = $this->createQueryBuilder('i')
            ->addOrderBy('i.id', 'DESC')
            ->getQuery()
            ->setMaxResults($maxperpage);
        $query->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
        return $query->getResult();
    }

    public function countUtilisateursTotal()
    {
        $qb = $this->createQueryBuilder('k');
        $qb->select('count(k)');

        $totaltypelogement = $qb->getQuery()->getSingleScalarResult();
        return $totaltypelogement;
    }

}
