<?php

namespace MonbonHLM\DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
    public function Recupererannonce($page=1, $maxperpage=9) {
        $query = $this->createQueryBuilder('i')
            ->addOrderBy('i.id', 'DESC')
            ->getQuery()
            ->setMaxResults($maxperpage);
        $query->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
        return $query->getResult();
    }

    public function Recupererannonceaccueil($page=1, $maxperpage=12) {
        $query = $this->createQueryBuilder('i')
            ->addOrderBy('i.id', 'DESC')
            ->getQuery()
            ->setMaxResults($maxperpage);
        $query->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
        return $query->getResult();
    }

    public function countAnnonceTotal()
    {
        $qb = $this->createQueryBuilder('k');
        $qb->select('count(k)');

        $totalannonces = $qb->getQuery()->getSingleScalarResult();
        return $totalannonces;
    }

    public function RecupererAnnonceParId($id)
    {
        $annonce = parent::find($id);
        return $annonce;
    }

    public function Auteurannonce($id) {
        $query = $this->createQueryBuilder('n')
            ->select('k')
            ->where('n.auteur = :identifier')
            ->setParameter('identifier', $id)
            ->getQuery();
        $query->setFirstResult(0);
        return $query->getResult();
    }
}
