<?php

namespace MonbonHLM\DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BailleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BailleurRepository extends EntityRepository
{
    public function Recupererbailleurs($page=1, $maxperpage=6) {
        $query = $this->createQueryBuilder('i')
            ->addOrderBy('i.id', 'DESC')
            ->getQuery()
            ->setMaxResults($maxperpage);
        $query->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
        return $query->getResult();
    }

    public function Recupererbailleursaccueil($page=1, $maxperpage=12) {
        $query = $this->createQueryBuilder('i')
            ->addOrderBy('i.id', 'DESC')
            ->getQuery()
            ->setMaxResults($maxperpage);
        $query->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
        return $query->getResult();
    }

    public function countbailleursTotal()
    {
        $qb = $this->createQueryBuilder('k');
        $qb->select('count(k)');

        $totalbailleurs = $qb->getQuery()->getSingleScalarResult();
        return $totalbailleurs;
    }

    public function RecupererbailleursParId($id)
    {
        $bailleurs = parent::find($id);
        return $bailleurs;
    }
}
