fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

monbon_hlm_home:
    resource: "@MonbonHLMHomeBundle/Resources/config/routing.yml"
    prefix:   /

monbonhlm_user:
    resource: "@MonbonHLMUserBundle/Resources/config/routing.yml"
    prefix:   /