services:
  monbonhlm_user.registration.form.type:
            class: MonbonHLM\UserBundle\Form\Type\RegistrationFormType
            tags:
                - { name: form.type, alias: monbonhlm_user_registration }
