######################  ANNONCES  #####################################

monbon_hlm_home_homepage:
    path:     /
    defaults: { _controller: MonbonHLMHomeBundle:Accueil:Recuperer }

monbon_hlm_home_annonces:
    path:     /annonces/{page}
    defaults: { _controller: MonbonHLMHomeBundle:Annonce:Recuperer, page: 1 }

monbon_hlm_home_details_annonces:
    path:     /annonce-{id}
    defaults: { _controller: MonbonHLMHomeBundle:Annonce:Detail }

monbon_hlm_home_ajouter_annonce:
    path:     /ajouter-annonce
    defaults: { _controller: MonbonHLMHomeBundle:Annonce:Ajouter }

monbon_hlm_home_modifier_annonce:
    path:     /modifier-annonce-{id}
    defaults: { _controller: MonbonHLMHomeBundle:Annonce:Modifier }

monbon_hlm_home_envoyer_message_annonceur:
    path:     /message-envoye/{id}
    defaults: { _controller: MonbonHLMHomeBundle:MessageAnnonce:Message }


######################  QUARTIERS  #####################################


monbon_hlm_home_quartier:
    path:     /quartiers
    defaults: { _controller: MonbonHLMHomeBundle:Quartier:Index, page: 1 }

monbon_hlm_home_annonces_quartier:
    path:     /annonces-quartier/{id}
    defaults: { _controller: MonbonHLMHomeBundle:Annonce:Quartier, page: 1 }

monbon_hlm_home_ajouter_quartier:
    path:     /ajouter-quartier
    defaults: { _controller: MonbonHLMHomeBundle:Quartier:Ajouter }


######################  TYPE DE LOGEMENTS  #####################################


monbon_hlm_home_type_logement:
    path:     /type-logements
    defaults: { _controller: MonbonHLMHomeBundle:TypeLogement:Index, page: 1 }

monbon_hlm_home_annonces_type_logement:
    path:     /annonces-typelogement/{id}
    defaults: { _controller: MonbonHLMHomeBundle:Annonce:Typelogement, page: 1 }


######################  BAILLEURS  #####################################


monbon_hlm_home_bailleurs:
    path:     /bailleurs
    defaults: { _controller: MonbonHLMHomeBundle:Bailleurs:Index, page: 1 }

monbon_hlm_home_modifier_bailleur:
    path:     /modifierbailleur-{id}
    defaults: { _controller: MonbonHLMHomeBundle:Bailleurs:modifierbailleur }

monbon_hlm_home_annonces_bailleur:
    path:     /annonces-bailleur/{id}
    defaults: { _controller: MonbonHLMHomeBundle:Annonce:Bailleurs, page: 1 }

######################  FAQ  #####################################


monbon_hlm_home_fonctionnement:
    path:     /fonctionnement
    defaults: { _controller: MonbonHLMHomeBundle:Faq:Fonctionnement }

monbon_hlm_home_demarches:
    path:     /demarches
    defaults: { _controller: MonbonHLMHomeBundle:Faq:Demarches }

monbon_hlm_home_questionsreponses:
    path:     /questions-reponses
    defaults: { _controller: MonbonHLMHomeBundle:Faq:Questionsreponses }
